ex14/dswd_blog/models/__init__.py
from .blog import Blog
from .user import User

__all__ = [
    'Blog',
    'User'
]

ex14/dswd_blog/models/blog.py
from ..extensions import db
import datetime as dt


class Blog(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    author_id = db.Column(db.Integer,
                          db.ForeignKey("user.id", ondelete='CASCADE'),
                          nullable=False)
    title = db.Column(db.String(128), nullable=False)
    content = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)

    def __repr__(self):
        return f"<Blog '{self.title}'>"

ex14/dswd_blog/models/user.py
from ..extensions import db, pwd_context, login_manager
import datetime as dt
from sqlalchemy import UniqueConstraint


@login_manager.user_loader
def load_user(user_id):
    """Load user by ID."""
    return User.query.get(int(user_id))


login_manager.login_view = "auth.sign_in"
login_manager.login_message = "Please sign in to access this page"


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30), nullable=False)
    email = db.Column(db.String(45), nullable=False)
    password = db.Column(db.String(255), nullable=False)

    active = db.Column(db.Boolean(), default=True)
    created_at = db.Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)

    __table_args__ = (
        UniqueConstraint('username', name='unique_username'),
        UniqueConstraint('email', name='unique_email'),
    )

    blogs = db.relationship("Blog",
                            backref="author",
                            cascade="all, delete-orphan")

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        self.password = pwd_context.hash(self.password)

    def set_password(self, password):
        """Set password."""
        self.password = pwd_context.hash(password)

    def check_password(self, value):
        """Check password."""
        return pwd_context.verify(value, self.password)

    @property
    def is_active(self):
        return True if self.active else False

    @property
    def is_authenticated(self):
        return True

    @property
    def is_anonymous(self):
        return False

    def get_id(self):
        return str(self.id)

ex14/dswd_blog/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired


class CreateBlog(FlaskForm):
    title = StringField(validators=[DataRequired(message="Title is a required field")])
    content = TextAreaField(validators=[DataRequired(message="Content is a required field")])


class EditBlog(CreateBlog):
    pass

ex14/dswd_blog/app.py
from flask import Flask
from . import auth, public, config, blog
from .extensions import db, migrate, login_manager, csrf_protect, mail
from . import models


def create_app(testing=False):
    app = Flask(__name__)

    if testing:
        app.config.from_object(config.TestingConfig)
    else:
        app.config.from_object(config.DevConfig)

    register_blueprints(app)
    register_extensions(app)

    return app


def register_blueprints(app):
    app.register_blueprint(auth.views.bp)
    app.register_blueprint(public.views.bp)
    app.register_blueprint(blog.views.bp)


def register_extensions(app):
    db.init_app(app)
    migrate.init_app(app, db)
    csrf_protect.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

ex14/dswd_blog/blog/__init__.py
from . import views

ex14/dswd_blog/blog/views.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, current_user
from .forms import CreateBlog, EditBlog
from ..models import Blog
from ..extensions import db


bp = Blueprint("blog", __name__, url_prefix="/blog")


@bp.route("/<int:page>")
@login_required
def home(page):
    blogs = Blog.query.order_by(Blog.id.desc()).paginate(per_page=5, page=page, error_out=True)
    # blogs = Blog.query.all()

    return render_template("blog/home/index.html", blogs=blogs)


@bp.route("/new/", methods=['GET', 'POST'])
@login_required
def create_blog():
    form = CreateBlog()

    if form.validate_on_submit():
        title = form.title.data
        content = form.title.data

        blog_obj = Blog(title=title, content=content, author=current_user)

        db.session.add(blog_obj)
        try:
            db.session.commit()
            return redirect(url_for('blog.home', page=1))
        except Exception as error:
            db.session.rollback()
            print(error)
            flash("Server error occured", "warning")

    return render_template("blog/create_blog/index.html", form=form)


@bp.route("/edit/<int:blog_id>", methods=['GET', 'POST'])
@login_required
def edit_blog(blog_id):
    blog_post = Blog.query.filter(Blog.author_id == current_user.id,
                                  Blog.id == blog_id).first_or_404()

    form = EditBlog()

    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.content = form.content.data

        try:
            db.session.commit()
            return redirect(url_for('blog.home', page=1))
        except Exception as error:
            db.session.rollback()
            print(error)
            flash("Server error occured", "warning")
    else:
        form.title.data = blog_post.title
        form.content.data = blog_post.content

    return render_template("blog/edit_blog/index.html", form=form)


@bp.route("/delete/<int:blog_id>", methods=['GET'])
@login_required
def delete_blog(blog_id):
    blog_post = Blog.query.filter_by(id=blog_id).first_or_404()

    db.session.delete(blog_post)
    try:
        db.session.commit()
    except Exception as error:
        db.session.rollback()
        print(error)
        flash("Server error occured", "warning")

    return redirect(url_for('blog.home', page=1))

ex14/dswd_blog/templates/blog/create_blog/form.html
<form method="POST" novalidate>
    {{ form.csrf_token() }}

    {% if form.title.errors %}
        <div>
            {{ form.title.errors[0] }}
        </div>
    {% endif %}

    <div>
        {{ form.title (placeholder="Title", type="text") }}
    </div>

    {% if form.content.errors %}
        <div>
            {{ form.content.errors[0] }}
        </div>
    {% endif %}

    <div>
        {{ form.content (placeholder="Content", type="text") }}
    </div>

    <div>
        <button type="submit">
            Post
        </button>
    </div>

</form>

ex14/dswd_blog/templates/blog/create_blog/index.html
{% extends "layout.html" %}

{% block content %}
<h2>Create Blog</h2>

{% include "blog/create_blog/form.html" %}
{% endblock %}


{% block title %}
Create Blog | DSWD
{% endblock %}

ex14/dswd_blog/templates/blog/edit_blog/form.html
<form method="POST" novalidate>
    {{ form.csrf_token() }}

    {% if form.title.errors %}
        <div>
            {{ form.title.errors[0] }}
        </div>
    {% endif %}

    <div>
        {{ form.title (placeholder="Title", type="text") }}
    </div>

    {% if form.content.errors %}
        <div>
            {{ form.content.errors[0] }}
        </div>
    {% endif %}

    <div>
        {{ form.content (placeholder="Content", type="text") }}
    </div>

    <div>
        <button type="submit">
            Save
        </button>
    </div>

</form>

ex14/dswd_blog/templates/blog/edit_blog/index.html
{% extends "layout.html" %}

{% block content %}
<h2>Edit Blog</h2>

{% include "blog/edit_blog/form.html" %}
{% endblock %}


{% block title %}
Edit Blog | DSWD
{% endblock %}

ex14/dswd_blog/templates/blog/home/blog_card.html
{% for data in blogs.items %}
<div class="blog_card">
    {% if current_user.id == data['author'].id %}
        <a href="{{ url_for('blog.edit_blog', blog_id=data['id']) }}">Edit</a>
        <a href="{{ url_for('blog.delete_blog', blog_id=data['id']) }}">Delete</a>
    {% endif %}
    <h3>
        {{ data['title'] }}
    </h3>

<!--    Try this:-->
<!--    .strftime('%Y-%m-%d')-->

    <p>{{ data['author'].username }} - {{ data['created_at'] }}</p>
    <p>{{ data['content'] }}</p>
</div>
{% endfor %}

ex14/dswd_blog/templates/blog/home/index.html
{% extends "layout.html" %}

{% block content %}
<h2>Welcome to our Blog</h2>

<a href="{{ url_for('blog.create_blog') }}">Create Post</a>

{% include "blog/home/blog_card.html" %}


{% for page in blogs.iter_pages(left_edge=3, right_edge=4, left_current=1, right_current=4) %}
    {% if page %}
        <a href="{{ url_for('blog.home', page=page) }}">{{ page }}</a>
    {% else %}
        ...
    {% endif %}
{% endfor %}

{% endblock %}


{% block title %}
Blog | DSWD
{% endblock %}

ex14/dswd_blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}DSWD Blog{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
</head>
<body>

{% include "nav.html" %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    {% for category, message in messages %}
        <div class="bg-{{ category }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% endwith %}

<main>
{% block content %}
{% endblock %}
</main>

</body>
</html>

ex14/dswd_blog/templates/nav.html
<nav>
    <a href="{{ url_for('public.home') }}">Home</a>
    <a href="{{ url_for('blog.home', page=1) }}">Blog</a>

    {% if current_user.is_authenticated %}
    <a href="{{ url_for('auth.sign_out') }}">Sign Out</a>
    {% else %}
    <a href="{{ url_for('auth.sign_in') }}">Sign In</a>
    {% endif %}
</nav>